# Generated by Django 4.2.3 on 2023-07-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_categoria", models.CharField(max_length=100)),
                ("imagem_categoria", models.ImageField(upload_to="imagens")),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cpf", models.CharField(max_length=14)),
                ("senha", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_produto", models.CharField(max_length=100)),
                ("valor", models.IntegerField()),
                ("descricao", models.TextField()),
                ("imagem_principal", models.ImageField(upload_to="")),
                ("imagem_1", models.ImageField(upload_to="")),
                ("imagem_2", models.ImageField(upload_to="")),
                ("imagem_3", models.ImageField(upload_to="")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.categoria",
                    ),
                ),
            ],
        ),
    ]
